"use client";

import { useCallback, useEffect, useState } from "react";
import type { ReactNode } from "react";
import { useRouter } from "next/navigation";

type Identity = { user: { name: string }; portal: string; redirectTo: string; activeContext: { agencyName?: string; clientName?: string } | null };
type Project = { id: string; name: string; status: string; priority: string; dueDate: string | null; progress: number; updatedAt?: string; upcomingMilestone?: { title: string; dueDate: string | null; status: string } | null };
type Update = { id: string; eventType: string; createdAt: string; actor?: { user: { name: string } } | null };
type SharedFile = { id: string; fileName: string; mimeType: string; sizeBytes: string; createdAt: string; project: { id: string; name: string } | null };
type Feedback = { id: string; title: string; description: string; status: string; createdAt: string; project: { id: string; name: string }; comments: Array<{ id: string; body: string; createdAt: string; author: { name: string } }> };
type Dashboard = { company: string; agency: string; metrics: { projects: number; pendingApprovals: number; sharedFiles: number }; projects: Project[]; upcomingDeadlines: Array<{ id: string; title: string; dueDate: string; kind: string; projectId: string }>; recentUpdates: Update[]; sharedFiles: SharedFile[] };
type ProjectDetail = { project: Project & { description: string | null; client: { companyName: string }; milestones: Array<{ id: string; title: string; status: string; dueDate: string | null }>; meetings: Array<{ id: string; title: string; scheduledAt: string; notes: string | null }>; feedback: Feedback[] }; updates: Update[]; sharedFiles: SharedFile[] };
async function api<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, { credentials: "include", ...init, headers: { "Content-Type": "application/json", ...init?.headers } }); const data = await response.json() as T & { error?: { message?: string } }; if (!response.ok) throw new Error(data.error?.message ?? "The request could not be completed."); return data; }
async function csrf(): Promise<Record<string, string>> { const { csrfToken } = await api<{ csrfToken: string }>("/api/v1/auth/csrf"); return { "X-CSRF-Token": csrfToken }; }
const date = (value?: string | null) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: value.includes("T") ? "short" : undefined }).format(new Date(value)) : "Not scheduled";
const statusLabel = (value: string) => value.replaceAll("_", " ").toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase());

export default function ClientPage() {
  const router = useRouter(); const [identity, setIdentity] = useState<Identity | null>(null); const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [projects, setProjects] = useState<Project[]>([]); const [feedback, setFeedback] = useState<Feedback[]>([]); const [files, setFiles] = useState<SharedFile[]>([]); const [detail, setDetail] = useState<ProjectDetail | null>(null); const [tab, setTab] = useState<"overview" | "projects" | "feedback" | "files">("overview"); const [formOpen, setFormOpen] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = useCallback(async () => {
    setError("");
    try {
      const me = await api<Identity>("/api/v1/auth/me"); setIdentity(me); if (me.portal !== "client") { router.replace(me.redirectTo); return; }
      const [dash, projectList, feedbackList, fileList] = await Promise.all([api<Dashboard>("/api/v1/client/dashboard"), api<{ items: Project[] }>("/api/v1/client/projects"), api<{ items: Feedback[] }>("/api/v1/client/feedback"), api<{ items: SharedFile[] }>("/api/v1/client/files")]);
      setDashboard(dash); setProjects(projectList.items); setFeedback(feedbackList.items); setFiles(fileList.items);
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not load the client portal."); }
  }, [router]);
  useEffect(() => { void load(); }, [load]);
  async function openProject(projectId: string) { try { setDetail(await api<ProjectDetail>(`/api/v1/client/projects/${projectId}`)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not load that project."); } }
  async function submitFeedback(form: FormData) { setBusy(true); setError(""); setNotice(""); try { await api("/api/v1/client/feedback", { method: "POST", headers: await csrf(), body: JSON.stringify({ projectId: form.get("projectId"), title: form.get("title"), description: form.get("description") }) }); setFormOpen(false); setNotice("Your feedback was sent to the agency."); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not send feedback."); } finally { setBusy(false); } }
  async function signOut() { try { await api("/api/v1/auth/logout", { method: "POST", headers: await csrf() }); router.replace("/login"); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not sign out."); } }
  if (!identity) return <main className="p-8 text-slate-600">Loading your portal…{error && <p role="alert" className="mt-2 text-rose-700">{error}</p>}</main>;
  const nav = { overview: "Overview", projects: "Projects", feedback: "Feedback", files: "Shared files" };
  return <main className="min-h-screen bg-[#f5f6fa] text-slate-900"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-indigo-700 font-black text-white">A</div><div><p className="text-sm font-black tracking-[.16em] text-indigo-700">APPZEX</p><p className="text-xs text-slate-500">{identity.activeContext?.agencyName ?? "Client portal"}</p></div></div><div className="flex items-center gap-4"><p className="hidden text-sm text-slate-600 sm:block">{identity.user.name} · {identity.activeContext?.clientName}</p><button onClick={() => void signOut()} className="rounded-lg border px-3 py-2 text-sm font-semibold">Sign out</button></div></div></header>
    <div className="mx-auto max-w-6xl px-6 py-8"><div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-indigo-700">CLIENT SPACE</p><h1 className="mt-1 text-3xl font-bold">Welcome, {dashboard?.company ?? identity.activeContext?.clientName}</h1><p className="mt-2 text-slate-500">Your projects and shared updates from {dashboard?.agency ?? identity.activeContext?.agencyName}.</p></div><button onClick={() => setFormOpen(true)} disabled={!projects.length} className="rounded-lg bg-indigo-700 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">＋ Send feedback</button></div>
      <div className="mb-6 flex flex-wrap gap-2">{Object.entries(nav).map(([key, label]) => <button key={key} onClick={() => setTab(key as typeof tab)} className={`rounded-lg px-4 py-2 text-sm font-semibold ${tab === key ? "bg-indigo-700 text-white" : "border border-slate-200 bg-white text-slate-600"}`}>{label}</button>)}</div>
      {error && <p role="alert" className="mb-4 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}{notice && <p role="status" className="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</p>}
      {tab === "overview" && dashboard && <><section className="grid gap-4 sm:grid-cols-3">{[["Projects", dashboard.metrics.projects], ["Pending approvals", dashboard.metrics.pendingApprovals], ["Shared files", dashboard.metrics.sharedFiles]].map(([label, value]) => <article key={String(label)} className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></article>)}</section><div className="mt-6 grid gap-6 lg:grid-cols-[1.4fr_1fr]"><section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-4 flex justify-between"><div><h2 className="text-lg font-bold">Your projects</h2><p className="text-sm text-slate-500">Progress reflects completed tasks.</p></div><button onClick={() => setTab("projects")} className="text-sm font-semibold text-indigo-700">View projects</button></div><ProjectCards items={dashboard.projects} onOpen={openProject}/></section><section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">Upcoming deadlines</h2>{dashboard.upcomingDeadlines.length ? dashboard.upcomingDeadlines.map((item) => <button key={`${item.kind}-${item.id}`} onClick={() => void openProject(item.projectId)} className="flex w-full justify-between gap-3 border-t py-3 text-left"><span className="font-semibold">{item.title}<span className="block text-xs font-normal text-slate-500">{statusLabel(item.kind)}</span></span><span className="whitespace-nowrap text-sm text-slate-500">{date(item.dueDate)}</span></button>) : <p className="py-8 text-sm text-slate-500">No upcoming deadlines.</p>}<h3 className="mt-5 font-bold">Shared updates</h3><Updates items={dashboard.recentUpdates}/></section></div><section className="mt-6 rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">Files shared with you</h2><FileList items={dashboard.sharedFiles}/></section></>}
      {tab === "projects" && <Panel title="Your projects"><ProjectCards items={projects} onOpen={openProject}/></Panel>}
      {tab === "feedback" && <Panel title="Feedback and approvals" action={<button onClick={() => setFormOpen(true)} disabled={!projects.length} className="rounded-lg bg-indigo-700 px-4 py-2 text-sm font-bold text-white">＋ New request</button>}><FeedbackList items={feedback}/></Panel>}
      {tab === "files" && <Panel title="Files shared with your company"><p className="mb-4 text-sm text-slate-500">Only files the agency marked as client shared appear here.</p><FileList items={files}/></Panel>}
    </div>
    {detail && <div className="fixed inset-0 z-40 flex justify-end bg-slate-950/30" onClick={() => setDetail(null)}><aside onClick={(event) => event.stopPropagation()} className="h-full w-full max-w-2xl overflow-y-auto bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-xs font-bold tracking-wide text-indigo-700">PROJECT DETAILS</p><h2 className="mt-1 text-2xl font-bold">{detail.project.name}</h2><p className="text-sm text-slate-500">{detail.project.client.companyName} · {statusLabel(detail.project.status)}</p></div><button onClick={() => setDetail(null)} className="rounded-lg border px-3 py-2">Close</button></div><div className="mt-5 rounded-xl bg-slate-50 p-4"><div className="flex justify-between text-sm"><strong>Progress</strong><span>{detail.project.progress}%</span></div><div className="mt-2 h-2 rounded-full bg-slate-200"><div className="h-2 rounded-full bg-indigo-600" style={{ width: `${detail.project.progress}%` }}/></div><p className="mt-3 text-sm text-slate-500">Due {date(detail.project.dueDate)}</p></div>{detail.project.description && <p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-slate-600">{detail.project.description}</p>}<h3 className="mt-7 font-bold">Milestones</h3>{detail.project.milestones.map((item) => <div key={item.id} className="flex justify-between border-b py-3 text-sm"><span>{item.title}<span className="ml-2 text-xs text-slate-500">{statusLabel(item.status)}</span></span><span className="text-slate-500">{date(item.dueDate)}</span></div>)}{!detail.project.milestones.length && <p className="mt-2 text-sm text-slate-500">No milestones yet.</p>}<h3 className="mt-7 font-bold">Shared meeting notes</h3>{detail.project.meetings.map((item) => <article key={item.id} className="border-b py-3"><p className="font-semibold">{item.title} · {date(item.scheduledAt)}</p>{item.notes && <p className="mt-1 whitespace-pre-wrap text-sm text-slate-600">{item.notes}</p>}</article>)}{!detail.project.meetings.length && <p className="mt-2 text-sm text-slate-500">No meeting notes have been shared.</p>}<h3 className="mt-7 font-bold">Feedback</h3><FeedbackList items={detail.project.feedback}/><h3 className="mt-7 font-bold">Files shared with you</h3><FileList items={detail.sharedFiles}/><h3 className="mt-7 font-bold">Shared updates</h3><Updates items={detail.updates}/></aside></div>}
    {formOpen && <Modal title="Send project feedback" close={() => setFormOpen(false)}><form action={(form) => void submitFeedback(form)} className="space-y-4"><SelectProject projects={projects}/><label className="block text-sm font-semibold">Title<input name="title" required minLength={4} maxLength={180} className="mt-1 w-full rounded-lg border px-3 py-2 font-normal" placeholder="What needs attention?"/></label><label className="block text-sm font-semibold">Details<textarea name="description" required minLength={10} maxLength={5000} rows={5} className="mt-1 w-full rounded-lg border px-3 py-2 font-normal" placeholder="Describe the change or issue…"/></label><div className="flex justify-end gap-2"><button type="button" onClick={() => setFormOpen(false)} className="rounded-lg border px-4 py-2 text-sm">Cancel</button><button disabled={busy} type="submit" className="rounded-lg bg-indigo-700 px-4 py-2 text-sm font-bold text-white">{busy ? "Sending…" : "Send request"}</button></div></form></Modal>}
  </main>;
}
function ProjectCards({ items, onOpen }: { items: Project[]; onOpen: (id: string) => void }) { return <div className="grid gap-3 md:grid-cols-2">{items.map((item) => <button key={item.id} onClick={() => onOpen(item.id)} className="rounded-xl border p-4 text-left transition hover:border-indigo-300 hover:shadow-sm"><div className="flex justify-between gap-3"><h3 className="font-bold">{item.name}</h3><span className="rounded-full bg-indigo-50 px-2.5 py-1 text-xs font-bold text-indigo-700">{statusLabel(item.status)}</span></div><div className="mt-4 flex justify-between text-xs text-slate-500"><span>Progress</span><span>{item.progress}%</span></div><div className="mt-1 h-1.5 rounded-full bg-slate-100"><div className="h-1.5 rounded-full bg-indigo-600" style={{ width: `${item.progress}%` }}/></div><p className="mt-3 text-xs text-slate-500">Due {date(item.dueDate)}{item.upcomingMilestone ? ` · Next: ${item.upcomingMilestone.title}` : ""}</p></button>)}{!items.length && <Empty>No projects have been shared with this company.</Empty>}</div>; }
function Updates({ items }: { items: Update[] }) { return <div className="mt-2 divide-y">{items.length ? items.map((item) => <div key={item.id} className="py-2 text-sm"><p className="font-medium">{statusLabel(item.eventType.replaceAll(".", " "))}</p><p className="text-xs text-slate-500">{item.actor?.user.name ?? "Shared update"} · {date(item.createdAt)}</p></div>) : <p className="py-4 text-sm text-slate-500">No shared updates yet.</p>}</div>; }
function FeedbackList({ items }: { items: Feedback[] }) { return <div className="divide-y">{items.length ? items.map((item) => <article key={item.id} className="py-4"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-bold">{item.title}</h3><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold">{statusLabel(item.status)}</span></div><p className="mt-1 text-xs text-indigo-700">{item.project.name} · {date(item.createdAt)}</p><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-600">{item.description}</p>{item.comments?.map((comment) => <div key={comment.id} className="mt-3 rounded-lg bg-slate-50 p-3 text-sm"><p className="whitespace-pre-wrap">{comment.body}</p><p className="mt-1 text-xs text-slate-500">{comment.author.name} · {date(comment.createdAt)}</p></div>)}</article>) : <Empty>No feedback requests yet.</Empty>}</div>; }
function FileList({ items }: { items: SharedFile[] }) { return <div className="mt-3 divide-y">{items.length ? items.map((file) => <div key={file.id} className="flex items-center justify-between gap-3 py-3"><div><p className="font-semibold">{file.fileName}</p><p className="text-xs text-slate-500">{file.project?.name ?? "Project file"} · {(Number(file.sizeBytes) / 1024).toFixed(0)} KB</p></div><a href={`/api/v1/files/${file.id}/download`} download className="text-sm font-semibold text-indigo-700">Download</a></div>) : <p className="py-6 text-sm text-slate-500">No files have been shared with your company.</p>}</div>; }
function Panel({ title, action, children }: { title: string; action?: ReactNode; children: ReactNode }) { return <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-bold">{title}</h2>{action}</div>{children}</section>; }
function Empty({ children }: { children: ReactNode }) { return <p className="col-span-full py-8 text-center text-sm text-slate-500">{children}</p>; }
function Modal({ title, close, children }: { title: string; close: () => void; children: ReactNode }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4" onClick={close}><section role="dialog" aria-modal="true" aria-label={title} onClick={(event) => event.stopPropagation()} className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><h2 className="mb-5 text-xl font-bold">{title}</h2>{children}</section></div>; }
function SelectProject({ projects }: { projects: Project[] }) { return <label className="block text-sm font-semibold">Project<select name="projectId" required className="mt-1 w-full rounded-lg border bg-white px-3 py-2 font-normal">{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label>; }


